### PR TITLE
[Kernel] Add enable_sm120_or_later for SM121 (DGX Spark) CUTLASS support

### LINKED ISSUE #28589: [Bug]: V1 Engine fails on Blackwell GB10 (SM 12.1): "sink setting not supported" by all compatible attention backends
### Your current environment

# [Bug] V1 Engine fails on Blackwell GB10 (SM 12.1): "sink setting not supported" by all compatible attention backends   
## System Information
   - **GPU**: NVIDIA GB10 (Blackwell architecture, SM 12.1)
   - **vLLM Version**: 0.11.1rc7.dev41+g6c3c0f823.d20251112
   - **PyTorch Version**: 2.6.0
   - **CUDA Version**: 13.0
   - **Python Version**: 3.12.3
   - **OS**: Linux 6.11.0-1016-nvidia

### Environment Setup
```bash
# Build vLLM from source (commit 6c3c0f823)
git clone https://github.com/vllm-project/vllm.git
cd vllm
git checkout 6c3c0f823

# Patch CUTLASS MoE to avoid undefined symbol error
# Comment out lines 256-264 in csrc/quantization/w8a8/cutlass/scaled_mm_entry.cu
# (SM100 CUTLASS MoE path - not compiled but referenced)

# Build
VLLM_TARGET_DEVICE=cuda MAX_JOBS=4 uv pip install -e .
```

### Attempted Commands

All of these fail with the same "sink setting not supported" error:

```bash
# Attempt 1: XFormers backend
export VLLM_USE_FLASHINFER_MOE_MXFP4_BF16=1
export VLLM_ATTENTION_BACKEND=XFORMERS
export VLLM_USE_V1=0
vllm serve openai/gpt-oss-120b \
  --quantization mxfp4 \
  --dtype bfloat16 \
  --max-model-len 16384 \
  --no-enable-prefix-caching

# Attempt 2: FlashInfer backend
export VLLM_ATTENTION_BACKEND=FLASHINFER
vllm serve openai/gpt-oss-120b \
  --quantization mxfp4 \
  --dtype bfloat16 \
  --max-model-len 16384 \
  --no-enable-prefix-caching

# Attempt 3: Flash Attention backend
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
vllm serve openai/gpt-oss-120b \
  --quantization mxfp4 \
  --dtype bfloat16 \
  --max-model-len 16384 \
  --no-enable-prefix-caching

# Attempt 4: Auto-select (picks Triton, which fails)
unset VLLM_ATTENTION_BACKEND
vllm serve openai/gpt-oss-120b \
  --quantization mxfp4 \
  --dtype bfloat16 \
  --max-model-len 16384 \
  --no-enable-prefix-caching
```
### XFormers/FlashInfer/Flash Attention Error
```
ValueError: Selected backend AttentionBackendEnum.XFORMERS is not valid for this configuration. Reason: ['sink setting not supported']
```

Full traceback:
```
File "/home/ohsono/vllm/vllm/platforms/cuda.py", line 370, in get_attn_backend_cls
  raise ValueError(
ValueError: Selected backend AttentionBackendEnum.XFORMERS is not valid for this configuration. Reason: ['sink setting not supported']
```

### Triton Backend Error (when auto-selected)
```
triton.runtime.errors.PTXASError: PTXAS error: Internal Triton PTX codegen error
`ptxas` stderr:
ptxas fatal : Value 'sm_121a' is not defined for option 'gpu-name'
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by Code4me2**
## Summary

Add `enable_sm120_or_later` kernel wrapper to support SM121 (DGX Spark GB10) in addition to SM120 (RTX 5090) for Blackwell CUTLASS kernels.

## Problem

DGX Spark GB10 (SM121) cannot use CUTLASS kernels because `enable_sm120_only` uses exact architecture match.

## Root Cause

The existing `enable_sm120_only` wrapper uses:
```cpp
#if defined __CUDA_ARCH__ && __CUDA_ARCH__ == 1200
```

This excludes SM121 (arch 1210) which has identical tensor core capabilities.

## Solution

Add new `enable_sm120_or_later` wrapper:
```cpp
#if defined __CUDA_ARCH__ && __CUDA_ARCH__ >= 1200
```

This includes both SM120 (RTX 5090) and SM121+ (DGX Spark) architectures.

## Files Changed

- `csrc/cutlass_extensions/common.hpp`: Add `enable_sm120_or_later` template
- `csrc/quantization/w8a8/cutlass/c3x/scaled_mm_blockwise_sm120_fp8_dispatch.cuh`: Use `enable_sm120_or_later` for FP8 blockwise GEMM

## Testing

Tested on DGX Spark GB10 (SM121) with `nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-NVFP4`

## Related Issues

Fixes #28589

### CODE REVIEW

File: csrc/cutlass_extensions/common.hpp [hunk 1]
```diff
@@ -70,3 +70,14 @@ struct enable_sm120_only : Kernel {
 #endif
   }
 };
+
+// SM12x family includes SM120 (RTX 5090) and SM121 (DGX Spark GB10)
+template <typename Kernel>
+struct enable_sm120_or_later : Kernel {
```
Comment (mgoin) [inline csrc/cutlass_extensions/common.hpp]: Let's update this to `enable_sm120_family` since "later" sounds like `>= sm120`

**Comment by Code4me2** [comment]
@mgoin was there anything else to do for this one? I think this PR has all the changes you wanted

**Review by mgoin — APPROVED** [review]

**Comment by mgoin** [comment]
Thanks @Code4me2 ! Enabled CI

**Comment by mgoin** [comment]
Nope just flaky CI at the moment, thanks for the ping!
