### PR TITLE
[Bugfix] Explicitly include "omp.h" for MacOS to avoid installation failure

### LINKED ISSUE #14034: [Installation]: Can't find OpenMP headers on macOS
Seems that clang can't find the OpenMP headers.

### Your current environment

```text
(vllm) ➜  vllm git:(v0.7.2) python collect_env.py 
INFO 02-28 18:13:24 __init__.py:190] Automatically detected platform cpu.
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.3.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.6)
CMake version: version 3.31.5
Libc version: N/A

Python version: 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 12:55:12) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==26.2.1
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.49.0
[conda] numpy                     1.26.4          py312h7f4fdc5_0  
[conda] numpy-base                1.26.4          py312he047099_0  
[conda] pyzmq                     26.2.1                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.49.0                   pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

LD_LIBRARY_PATH=/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages/cv2/../../lib:
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1


```

### How you are installing vllm

```sh
(vllm) ➜  vllm git:(v0.7.2) pip install -e .            
Obtaining file:///Users/shengyao/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: psutil in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (7.0.0)
Requirement already satisfied: sentencepiece in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.2.0)
Requirement already satisfied: numpy<2.0.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (1.26.4)
Requirement already satisfied: requests>=2.26.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (2.32.3)
Requirement already satisfied: tqdm in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (4.67.1)
Requirement already satisfied: blake3 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (1.0.4)
Requirement already satisfied: py-cpuinfo in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (9.0.0)
Requirement already satisfied: transformers>=4.48.2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (4.49.0)
Requirement already satisfied: tokenizers>=0.19.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.21.0)
Requirement already satisfied: protobuf in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (5.29.3)
Requirement already satisfied: fastapi!=0.113.*,!=0.114.0,>=0.107.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.115.9)
Requirement already satisfied: aiohttp in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (3.11.13)
Requirement already satisfied: openai>=1.52.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (1.65.1)
Requirement already satisfied: uvicorn[standard] in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.34.0)
Requirement already satisfied: pydantic>=2.9 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (2.10.6)
Requirement already satisfied: prometheus_client>=0.18.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.21.1)
Requirement already satisfied: pillow in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (11.1.0)
Requirement already satisfied: prometheus-fastapi-instrumentator>=7.0.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (7.0.2)
Requirement already satisfied: tiktoken>=0.6.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.9.0)
Requirement already satisfied: lm-format-enforcer<0.11,>=0.10.9 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.10.11)
Requirement already satisfied: outlines==0.1.11 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.1.11)
Requirement already satisfied: lark==1.2.2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (1.2.2)
Requirement already satisfied: typing_extensions>=4.10 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (4.12.2)
Requirement already satisfied: filelock>=3.16.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (3.17.0)
Requirement already satisfied: partial-json-parser in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.2.1.1.post5)
Requirement already satisfied: pyzmq in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (26.2.1)
Requirement already satisfied: msgspec in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.19.0)
Requirement already satisfied: gguf==0.10.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.10.0)
Requirement already satisfied: importlib_metadata in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (8.6.1)
Requirement already satisfied: mistral_common>=1.5.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from mistral_common[opencv]>=1.5.0->vllm==0.7.2+cpu) (1.5.3)
Requirement already satisfied: pyyaml in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (6.0.2)
Requirement already satisfied: six>=1.16.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (1.17.0)
Requirement already satisfied: setuptools>=74.1.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (75.8.0)
Requirement already satisfied: einops in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.8.1)
Requirement already satisfied: compressed-tensors==0.9.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.9.1)
Requirement already satisfied: depyf==0.18.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.18.0)
Requirement already satisfied: cloudpickle in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (3.1.1)
Requirement already satisfied: torch==2.5.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (2.5.1)
Requirement already satisfied: torchaudio in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (2.5.1)
Requirement already satisfied: torchvision in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (0.20.1)
Requirement already satisfied: datasets in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from vllm==0.7.2+cpu) (3.3.2)
Requirement already satisfied: astor in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from depyf==0.18.0->vllm==0.7.2+cpu) (0.8.1)
Requirement already satisfied: dill in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from depyf==0.18.0->vllm==0.7.2+cpu) (0.3.8)
Requirement already satisfied: interegular in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (0.3.3)
Requirement already satisfied: jinja2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (3.1.5)
Requirement already satisfied: nest_asyncio in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (1.6.0)
Requirement already satisfied: diskcache in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (5.6.3)
Requirement already satisfied: referencing in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (0.36.2)
Requirement already satisfied: jsonschema in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (4.23.0)
Requirement already satisfied: pycountry in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (24.6.1)
Requirement already satisfied: airportsdata in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (20250224)
Requirement already satisfied: outlines_core==0.1.26 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from outlines==0.1.11->vllm==0.7.2+cpu) (0.1.26)
Requirement already satisfied: networkx in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from torch==2.5.1->vllm==0.7.2+cpu) (3.4.2)
Requirement already satisfied: fsspec in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from torch==2.5.1->vllm==0.7.2+cpu) (2024.12.0)
Requirement already satisfied: sympy==1.13.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from torch==2.5.1->vllm==0.7.2+cpu) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.5.1->vllm==0.7.2+cpu) (1.3.0)
Requirement already satisfied: starlette<0.46.0,>=0.40.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from fastapi!=0.113.*,!=0.114.0,>=0.107.0->vllm==0.7.2+cpu) (0.45.3)
Requirement already satisfied: packaging in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from lm-format-enforcer<0.11,>=0.10.9->vllm==0.7.2+cpu) (24.2)
Requirement already satisfied: opencv-python-headless>=4.0.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from mistral_common[opencv]>=1.5.0->vllm==0.7.2+cpu) (4.11.0.86)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from openai>=1.52.0->vllm==0.7.2+cpu) (4.8.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from openai>=1.52.0->vllm==0.7.2+cpu) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from openai>=1.52.0->vllm==0.7.2+cpu) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from openai>=1.52.0->vllm==0.7.2+cpu) (0.8.2)
Requirement already satisfied: sniffio in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from openai>=1.52.0->vllm==0.7.2+cpu) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from pydantic>=2.9->vllm==0.7.2+cpu) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from pydantic>=2.9->vllm==0.7.2+cpu) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from requests>=2.26.0->vllm==0.7.2+cpu) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from requests>=2.26.0->vllm==0.7.2+cpu) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from requests>=2.26.0->vllm==0.7.2+cpu) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from requests>=2.26.0->vllm==0.7.2+cpu) (2025.1.31)
Requirement already satisfied: regex>=2022.1.18 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from tiktoken>=0.6.0->vllm==0.7.2+cpu) (2024.11.6)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from tokenizers>=0.19.1->vllm==0.7.2+cpu) (0.29.1)
Requirement already satisfied: safetensors>=0.4.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from transformers>=4.48.2->vllm==0.7.2+cpu) (0.5.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from aiohttp->vllm==0.7.2+cpu) (1.18.3)
Requirement already satisfied: pyarrow>=15.0.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from datasets->vllm==0.7.2+cpu) (19.0.1)
Requirement already satisfied: pandas in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from datasets->vllm==0.7.2+cpu) (2.2.3)
Requirement already satisfied: xxhash in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from datasets->vllm==0.7.2+cpu) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from datasets->vllm==0.7.2+cpu) (0.70.16)
Requirement already satisfied: zipp>=3.20 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from importlib_metadata->vllm==0.7.2+cpu) (3.21.0)
Requirement already satisfied: click>=7.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (8.1.8)
Requirement already satisfied: h11>=0.8 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (0.14.0)
Requirement already satisfied: httptools>=0.6.3 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (0.6.4)
Requirement already satisfied: python-dotenv>=0.13 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (1.0.1)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (0.21.0)
Requirement already satisfied: watchfiles>=0.13 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (1.0.4)
Requirement already satisfied: websockets>=10.4 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from uvicorn[standard]->vllm==0.7.2+cpu) (15.0)
Requirement already satisfied: httpcore==1.* in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai>=1.52.0->vllm==0.7.2+cpu) (1.0.7)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from jsonschema->outlines==0.1.11->vllm==0.7.2+cpu) (2024.10.1)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from jsonschema->outlines==0.1.11->vllm==0.7.2+cpu) (0.23.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from jinja2->outlines==0.1.11->vllm==0.7.2+cpu) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from pandas->datasets->vllm==0.7.2+cpu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from pandas->datasets->vllm==0.7.2+cpu) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages (from pandas->datasets->vllm==0.7.2+cpu) (2025.1)
Building wheels for collected packages: vllm
  Building editable for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]
      /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      VLLM_TARGET_DEVICE automatically set to `cpu` due to macOS
      running editable_wheel
      creating /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info
      writing /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/entry_points.txt
      writing requirements to /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/requires.txt
      writing top-level names to /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/top_level.txt
      writing manifest file '/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm.egg-info/SOURCES.txt'
      creating '/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm-0.7.2+cpu.dist-info'
      creating /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-wheel-0gh_7xri/.tmp-k7cx31nn/vllm-0.7.2+cpu.dist-info/WHEEL
      running build_py
      running build_ext
      -- The CXX compiler identification is AppleClang 16.0.0.16000026
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Build type: RelWithDebInfo
      -- Target device: cpu
      -- Found Python: /Users/shengyao/anaconda3/envs/vllm/bin/python (found version "3.12.9") found components: Interpreter Development.Module Development.SABIModule
      -- Found python matching: /Users/shengyao/anaconda3/envs/vllm/bin/python.
      CMake Warning at /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
        static library kineto_LIBRARY-NOTFOUND not found.
      Call Stack (most recent call first):
        /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:120 (append_torchlib_if_found)
        CMakeLists.txt:81 (find_package)
      
      
      -- Found Torch: /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/lib/libtorch.dylib
      -- Apple Silicon Detected
      -- CPU extension compile flags: -Xpreprocessor;-fopenmp;-DVLLM_CPU_EXTENSION
      -- NUMA is disabled
      -- Enabling C extension.
      -- Configuring done (1.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/tmplepo0g_7.build-temp
      [1/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/attention.cpp.o
      FAILED: CMakeFiles/_C.dir/csrc/cpu/attention.cpp.o
      ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPy_LIMITED_API=3 -DTORCH_EXTENSION_NAME=_C -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -DVLLM_NUMA_DISABLED -D_C_EXPORTS -I/Users/shengyao/vllm/csrc -isystem /Users/shengyao/anaconda3/envs/vllm/include/python3.12 -isystem /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/include -isystem /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -O2 -g -DNDEBUG -std=gnu++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -fPIC -Xpreprocessor -fopenmp -DVLLM_CPU_EXTENSION -MD -MT CMakeFiles/_C.dir/csrc/cpu/attention.cpp.o -MF CMakeFiles/_C.dir/csrc/cpu/attention.cpp.o.d -o CMakeFiles/_C.dir/csrc/cpu/attention.cpp.o -c /Users/shengyao/vllm/csrc/cpu/attention.cpp
      /Users/shengyao/vllm/csrc/cpu/attention.cpp:281:40: error: use of undeclared identifier 'omp_get_max_threads'
        281 |     const int parallel_work_item_num = omp_get_max_threads();
            |                                        ^
      /Users/shengyao/vllm/csrc/cpu/attention.cpp:301:22: error: use of undeclared identifier 'omp_get_thread_num'; did you mean 'at::get_thread_num'?
        301 |             logits + omp_get_thread_num() * max_seq_len_padded;
            |                      ^~~~~~~~~~~~~~~~~~
            |                      at::get_thread_num
      /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/torch/include/ATen/Parallel.h:24:15: note: 'at::get_thread_num' declared here
         24 | TORCH_API int get_thread_num();
            |               ^
      2 errors generated.
      [2/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/utils.cpp.o
      [3/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/layernorm.cpp.o
      [4/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/cache.cpp.o
      [5/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/pos_encoding.cpp.o
      [6/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/activation.cpp.o
      [7/8] Building CXX object CMakeFiles/_C.dir/csrc/cpu/torch_bindings.cpp.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 139, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 340, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 263, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 290, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "<string>", line 249, in run
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
          self.build_extensions()
        File "<string>", line 220, in build_extensions
        File "/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/subprocess.py", line 415, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j=10', '--target=_C']' returned non-zero exit status 1.
      /private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:1002: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `vllm` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 303, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 476, in build_editable
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 631, in <module>
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 139, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 340, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 263, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 290, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "<string>", line 249, in run
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/private/var/folders/y3/3jtypt212bb1qgh729dpkklr0000gn/T/pip-build-env-wdxq_9mv/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
          self.build_extensions()
        File "<string>", line 220, in build_extensions
        File "/Users/shengyao/anaconda3/envs/vllm/lib/python3.12/subprocess.py", line 415, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j=10', '--target=_C']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for vllm
Failed to build vllm
ERROR: Failed to build installable wheels for some pyproject.toml based projects (vllm)

```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by realShengYao**
If we detect MacOS, explicitly include "omp.h". This helps to avoid the installation failure mentioned in #14034 .

FIX #14034

### CODE REVIEW

File: csrc/cpu/cpu_types.hpp [hunk 1]
```diff
@@ -1,6 +1,10 @@
 #ifndef CPU_TYPES_HPP
 #define CPU_TYPES_HPP
 
+#if defined(__APPLE__)
+  #include "omp.h"
+#endif
+
```
Comment (hmellor) [inline csrc/cpu/cpu_types.hpp:7]: Could you move this into `cpu_types_arm.hpp`?

Comment (realShengYao) [reply csrc/cpu/cpu_types.hpp:7]: Sure, I'm happy to do it.

Comment (realShengYao) [reply csrc/cpu/cpu_types.hpp:7]: Do you also want me to add some notes for it in the docs by the way?

Comment (hmellor) [reply csrc/cpu/cpu_types.hpp:7]: If Apple Clang truly does not work then yes we should update the docs to recommend the correct compiler. Let's see what the conclusion is in your original issue.

Comment (realShengYao) [reply csrc/cpu/cpu_types.hpp:7]: Absolutely.

**Review by hmellor — APPROVED** [review]

**Comment by hmellor** [comment]
@realShengYao is this ready to be converted from draft?

**Comment by realShengYao** [comment]
@hmellor yes yes

**Comment by hmellor** [comment]
Cool, could you merge from main so (the failing test should be fixed already) and then I'll enable auto-merge

**Comment by realShengYao** [comment]
Sure. Should be okay to auto merge now.

**Comment by hmellor** [comment]
Thanks again for the bugfix!

**Comment by realShengYao** [comment]
You're most welcome!
