### PR TITLE
[Hardware][CPU] Add embedding models support for CPU backend

### LINKED ISSUE #9379: [Bug]: Unable to embed any text using the vLLM CPU server
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
WARNING 10-15 15:52:41 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 10-15 15:52:41 importing.py:10] Triton not installed; certain GPU-related functions will not be available.
PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.30.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.8.0-1015-aws-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               36
On-line CPU(s) list:                  0-35
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
CPU family:                           6
Model:                                85
Thread(s) per core:                   2
Core(s) per socket:                   18
Socket(s):                            1
Stepping:                             4
BogoMIPS:                             6000.01
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            576 KiB (18 instances)
L1i cache:                            576 KiB (18 instances)
L2 cache:                             18 MiB (18 instances)
L3 cache:                             24.8 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-35
Vulnerability Gather data sampling:   Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:          KVM: Mitigation: VMX unsupported
Vulnerability L1tf:                   Mitigation; PTE Inversion
Vulnerability Mds:                    Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:               Mitigation; PTI
Vulnerability Mmio stale data:        Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Vulnerable
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Vulnerable
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Retpoline
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0+cpu
[pip3] torchvision==0.19.0+cpu
[pip3] transformers==4.45.2
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.dev8+ge9d517f2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

</details>

### Model Input Dumps

_No response_

### 🐛 Describe the bug

The OpenAI Embeddings endpoint (/v1/embeddings) served by the vLLM server (CPU) throws the following exception:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/avi/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ubuntu/avi/vllm/vllm/entrypoints/openai/api_server.py", line 343, in create_embedding
    generator = await embedding(raw_request).create_embedding(
  File "/home/ubuntu/avi/vllm/vllm/entrypoints/openai/serving_embedding.py", line 177, in create_embedding
    async for i, res in result_generator:
  File "/home/ubuntu/avi/vllm/vllm/utils.py", line 496, in merge_async_iterators
    item = await d
  File "/home/ubuntu/avi/vllm/vllm/engine/multiprocessing/client.py", line 591, in _process_request
    raise request_output
TypeError: 'NoneType' object is not subscriptable
INFO 10-15 15:51:22 logger.py:37] Received request embd-acc4b5d311844bd7b395734f15523975-0: prompt: 'Hello my name is', params: PoolingParams(additional_metadata=None), prompt_token_ids: [1, 22557, 586, 1141, 349, 2], lora_request: None, prompt_adapter_request: None.
INFO 10-15 15:51:22 logger.py:37] Received request embd-acc4b5d311844bd7b395734f15523975-1: prompt: 'The best thing about vLLM is that it supports many different models', params: PoolingParams(additional_metadata=None), prompt_token_ids: [1, 415, 1489, 1970, 684, 363, 5292, 28755, 349, 369, 378, 11562, 1287, 1581, 4994, 2], lora_request: None, prompt_adapter_request: None.
CRITICAL 10-15 15:51:22 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:36704 - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
```

upon running the below script,

```
from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key=openai_api_key,
    base_url=openai_api_base,
)

models = client.models.list()
model = models.data[0].id

responses = client.embeddings.create(
    input=[
        "Hello my name is",
        "The best thing about vLLM is that it supports many different models"
    ],
    model=model,
)

for data in responses.data:
    print(data.embedding)  # list of float of len 4096

```

I have used the following command to invoke vLLM CPU server.

```
python -m vllm.entrypoints.openai.api_server --model intfloat/e5-mistral-7b-instruct  --dtype float32 --download-dir ../models/ --port 8000
```

Same issue happens with the vlLM cpu installation using Dockerfile.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by Isotr0py**
FIX #9379 
- Implement CPU embedding model runner
- Add encoder-only attention support to SDPA backend

### CODE REVIEW

File: .buildkite/run-cpu-test.sh [hunk 1]
```diff
@@ -32,8 +32,7 @@ function cpu_tests() {
       decord einops librosa peft Pillow sentence-transformers soundfile \
       transformers_stream_generator matplotlib datamodel_code_generator
     pip install torchvision --index-url https://download.pytorch.org/whl/cpu
-    # Embedding models are not supported for CPU yet
-    # pytest -v -s tests/models/embedding/language
```
Comment (DarkLight1337) [inline .buildkite/run-cpu-test.sh:36]: Don't forget to also update `run-cpu-test-ppc64le.sh`!

File: vllm/model_executor/models/bert.py [hunk 2]
```diff
@@ -216,11 +215,6 @@ def __init__(
                               quant_config=quant_config,
                               prefix=f"{prefix}.attn")
 
-        if not isinstance(self.attn.impl, XFormersImpl):
-            raise ValueError(
-                "Encoder-only models currently require XFORMERS attention "
-                "backend. Set VLLM_ATTENTION_BACKEND=XFORMERS to use BERT.")
```
Comment (DarkLight1337) [inline vllm/model_executor/models/bert.py:222]: Accordingly, we should remove the env override in `tests/models/embedding/language/test_embedding.py` since it's no longer necessary.

File: tests/models/embedding/language/test_embedding.py [hunk 3]
```diff
@@ -21,15 +23,14 @@
...
     hf_runner,
     vllm_runner,
     example_prompts,
     model,
     dtype: str,
 ) -> None:
-    if model in ENCODER_ONLY:
-        monkeypatch.setenv("VLLM_ATTENTION_BACKEND", "XFORMERS")
+    if model not in ENCODER_ONLY and current_platform.is_cpu():
+        pytest.skip("Skip large embedding models test on CPU.")
```
Comment (Isotr0py) [inline tests/models/embedding/language/test_embedding.py:33]: I only enable encoder-only model test here, because gemma2 is only supported on GPU and e5-mistral-7b might significantly slow down the test.

Comment (DarkLight1337) [reply tests/models/embedding/language/test_embedding.py:33]: Sounds good to me.

**Review by DarkLight1337 — APPROVED** [review]
Looks good overall, see if the tests pass.

In the future we should also add `core_model` and `cpu_model` tags to embedding model tests.

**Comment by DarkLight1337** [comment]
Oh, the test failed but the CI still passed 😅

**Comment by Isotr0py** [comment]
Ah, the encoder-decoder tests are broken due to runner refactor. Let me make a quick PR to fix it. 😅

**Comment by Isotr0py** [comment]
I have opened #10218 to fix the broken encoder-decoder CPU runner.

**Comment by DarkLight1337** [comment]
> Hi everyone @Isotr0py @DarkLight1337 Is it possible to have an example on how to launch vllm on cpu with an embedding model ? Having a hard time to see how this works
> 
> Thanks in advance

You can use `vllm serve <model> --task embedding`.

**Comment by githebs** [comment]
Thanks for the reply and sorry to bother you for that once more but here is my compose 

```
services:
  vllm:
      container_name: vllm
      image: vllm/vllm-openai:latest
      restart: unless-stopped
      shm_size: '64gb'
      command: --host 0.0.0.0 --model /models/HIT-TMG-KaLM-embedding-multilingual-mini-instruct-v1 --max-model-len 32768 --device cpu --task embedding
      environment:
        - ENGINE_ITERATION_TIMEOUT_S=180
      volumes:
        - /models/:/models
      ports:
        - 9000:8000
```

got console error 

```
INFO 11-25 06:52:13 api_server.py:585] vLLM API server version 0.6.4.post1
INFO 11-25 06:52:13 api_server.py:586] args: Namespace(host='0.0.0.0', port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='/models/HIT-TMG-KaLM-embedding-multilingual-mini-instruct-v1', task='embedding', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', chat_template_text_format='string', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=32768, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='cpu', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
INFO 11-25 06:52:13 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/b0f1e755-446e-4ad2-9e5e-23bd11657abc for IPC Path.
INFO 11-25 06:52:13 api_server.py:194] Started engine process with PID 16
INFO 11-25 06:52:13 config.py:1861] Downcasting torch.float32 to torch.float16.
INFO 11-25 06:52:17 config.py:1861] Downcasting torch.float32 to torch.float16.
WARNING 11-25 06:52:17 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
WARNING 11-25 06:52:17 config.py:487] Async output processing is only supported for CUDA, TPU, XPU and HPU.Disabling it for other platforms.
WARNING 11-25 06:52:20 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
WARNING 11-25 06:52:20 config.py:487] Async output processing is only supported for CUDA, TPU, XPU and HPU.Disabling it for other platforms.
INFO 11-25 06:52:20 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='/models/HIT-TMG-KaLM-embedding-multilingual-mini-instruct-v1', speculative_config=None, tokenizer='/models/HIT-TMG-KaLM-embedding-multilingual-mini-instruct-v1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/models/HIT-TMG-KaLM-embedding-multilingual-mini-instruct-v1, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=False, use_cached_outputs=True, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=PoolerConfig(pooling_type='MEAN', normalize=True, softmax=None, step_tag_id=None, returned_token_ids=None))
WARNING 11-25 06:52:20 cpu_executor.py:320] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 11-25 06:52:20 cpu_executor.py:350] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 11-25 06:52:20 selector.py:261] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 11-25 06:52:20 selector.py:144] Using XFormers backend.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
ERROR 11-25 06:52:24 engine.py:366] There is no module or parameter named 'embed_tokens' in Qwen2EmbeddingModel
ERROR 11-25 06:52:24 engine.py:366] Traceback (most recent call last):
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 11-25 06:52:24 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 11-25 06:52:24 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 11-25 06:52:24 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 11-25 06:52:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 11-25 06:52:24 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 11-25 06:52:24 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 11-25 06:52:24 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 11-25 06:52:24 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 11-25 06:52:24 engine.py:366]     self._init_executor()
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 121, in _init_executor
ERROR 11-25 06:52:24 engine.py:366]     self._run_workers("load_model")
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 181, in _run_workers
ERROR 11-25 06:52:24 engine.py:366]     driver_worker_output = self.driver_method_invoker(
ERROR 11-25 06:52:24 engine.py:366]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 373, in _driver_method_invoker
ERROR 11-25 06:52:24 engine.py:366]     return getattr(driver, method)(*args, **kwargs)
ERROR 11-25 06:52:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/cpu_worker.py", line 206, in load_model
ERROR 11-25 06:52:24 engine.py:366]     self.model_runner.load_model()
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/cpu_model_runner.py", line 469, in load_model
ERROR 11-25 06:52:24 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 11-25 06:52:24 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 11-25 06:52:24 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 11-25 06:52:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
ERROR 11-25 06:52:24 engine.py:366]     model.load_weights(self._get_all_weights(model_config, model))
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 570, in load_weights
ERROR 11-25 06:52:24 engine.py:366]     loader.load_weights(weights)
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 229, in load_weights
ERROR 11-25 06:52:24 engine.py:366]     autoloaded_weights = list(self._load_module("", self.module, weights))
ERROR 11-25 06:52:24 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-25 06:52:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 218, in _load_module
ERROR 11-25 06:52:24 engine.py:366]     raise ValueError(msg)
**_ERROR 11-25 06:52:24 engine.py:366] ValueError: There is no module or parameter named 'embed_tokens' in Qwen2EmbeddingModel_**
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 121, in _init_executor
    self._run_workers("load_model")
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 181, in _run_workers
    driver_worker_output = self.driver_method_invoker(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/cpu_executor.py", line 373, in _driver_method_invoker
    return getattr(driver, method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/cpu_worker.py", line 206, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/cpu_model_runner.py", line 469, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
    return loader.load_model(vllm_config=vllm_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
    model.load_weights(self._get_all_weights(model_config, model))
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 570, in load_weights
    loader.load_weights(weights)
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 229, in load_weights
    autoloaded_weights = list(self._load_module("", self.module, weights))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 218, in _load_module
    raise ValueError(msg)
ValueError: There is no module or parameter named 'embed_tokens' in Qwen2EmbeddingModel
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 643, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 609, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 113, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 210, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
```

Any hint ?

**Comment by DarkLight1337** [comment]
Can you try overriding the architecture name to `Qwen2ForCausalLM` via `--hf-override '{"architectures": ["Qwen2ForCausalLM"]}'`?

**Comment by DarkLight1337** [comment]
Please try #10639 and see if it fixes your issue
