### PR TITLE
[Bugfix] fix gettid method is not define

### LINKED ISSUE #16066: [Bug]: gettid() undefined in `vllm_source/csrc/cpu/utils.cpp`
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>
Can't display it publicly but amd64 modern cpu, very high ram, using cpu platform

</details>

### 🐛 Describe the bug

Bug faced when running `VLLM_TARGET_DEVICE=cpu python setup.py install`

The fix I found is to add
```c
#include <unistd.h>
#include <sys/syscall.h>
#define gettid() syscall(SYS_gettid)
```
in  `vllm_source/csrc/cpu/utils.cpp`

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by lengrongfu**
FIX https://github.com/vllm-project/vllm/issues/16066

### CODE REVIEW

**Comment by lengrongfu** [comment]
@DarkLight1337 Can you take a look? Thanks

File: csrc/cpu/utils.cpp [hunk 1]
```diff
@@ -4,6 +4,9 @@
   #include <string>
   #include <sched.h>
 #endif
+#include <unistd.h>
+#include <sys/syscall.h>
+#define gettid() syscall(SYS_gettid)
```
Comment (bigPYJ1151) [inline csrc/cpu/utils.cpp:9]:
```suggestion
#if __GLIBC__ == 2 && __GLIBC_MINOR__ < 30
  #include <unistd.h>
  #include <sys/syscall.h>
  #define gettid() syscall(SYS_gettid)
#endif
```
Perhaps applying this usage to specific glibc versions is better.

Comment (lengrongfu) [reply csrc/cpu/utils.cpp:9]: thanks you suggestion. i will update code.

**Comment by bigPYJ1151** [comment]
LGTM, please help to take a look @DarkLight1337 , thanks :)

**Review by DarkLight1337 — APPROVED** [review]
Stamp
